use_frameworks!

platform :ios, '10.0'

target 'DarkStarPhotoBrowserKit_Example' do
  pod 'DarkStarPhotoBrowserKit', :path => '../'

  target 'DarkStarPhotoBrowserKit_Tests' do
    inherit! :search_paths

    
  end
end
