# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test-channel-pack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test-channel-pack

  target 'test-channel-packTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test-channel-packUITests' do
    # Pods for testing
  end

end
