use_frameworks!

platform :ios, '10.0'

target 'DarkStarEnjoyCameraKit_Example' do
  pod 'DarkStarEnjoyCameraKit', :path => '../'

  target 'DarkStarEnjoyCameraKit_Tests' do
    inherit! :search_paths

    
  end
end
