use_frameworks!

platform :ios, '10.0'

target 'DarkStarAwesomeKit_Example' do
  pod 'DarkStarAwesomeKit', :path => '../'

  target 'DarkStarAwesomeKit_Tests' do
    inherit! :search_paths

    
  end
end
