# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DarkStar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'DarkStarConfiguration', :path => '../CommonPods/DarkStarConfiguration/'
  pod 'DarkStarBaseKit', :path => '../CommonPods/DarkStarBaseKit/'
  pod 'DarkStarUIKit', :path => '../CommonPods/DarkStarUIKit/'
  pod 'DarkStarScanKit', :path => '../CommonPods/DarkStarScanKit/'
  pod 'DarkStarGrayViewKit', :path => '../CommonPods/DarkStarGrayViewKit/'
  pod 'DarkStarAuthorityKit', :path => '../CommonPods/DarkStarAuthorityKit/'
  pod 'DarkStarGeneralTools', :path => '../CommonPods/DarkStarGeneralTools/'
  pod 'DarkStarUpdateSDK', :path => '../CommonPods/DarkStarUpdateSDK/'
  pod 'DarkStarCrypto', :path => '../CommonPods/DarkStarCrypto/'
  pod 'DarkStarAudioRecorderKit', :path => '../CommonPods/DarkStarAudioRecorderKit/'
  pod 'DarkStarThirdPartyKit', :path => '../CommonPods/DarkStarThirdPartyKit/'
  pod 'DarkStarKeepAliveManager', :path => '../CommonPods/DarkStarKeepAliveManager/'
  pod 'DarkStarUIComponents', :path => '../CommonPods/DarkStarUIComponents/'
  pod 'DarkStarQMUI', :path => '../CommonPods/DarkStarQMUI/'
  pod 'DarkStarDataStoreKit', :path => '../CommonPods/DarkStarDataStoreKit/'
  pod 'DarkStarFeedKit', :path => '../CommonPods/DarkStarFeedKit/'
  pod 'DarkStarNetWorkKit', :path => '../CommonPods/DarkStarNetWorkKit/'
  pod 'DarkStarAccountKit', :path => '../CommonPods/DarkStarAccountKit/'
  pod 'DarkStarWebKit', :path => '../CommonPods/DarkStarWebKit/'
  pod 'DarkStarResourceKit', :path => '../CommonPods/DarkStarResourceKit/'
  pod 'DarkStarAwesomeKit', :path => '../CommonPods/DarkStarAwesomeKit/'
  pod 'DarkStarDownloadManagerKit', :path => '../CommonPods/DarkStarDownloadManagerKit/'
  
  #NrLottieBridge使用Swift版本，NrLottieMixView使用OC版本；这两个库不能同时用
  pod 'NrLottieBridge', :path => '../CommonPods/NrLottieBridge/'
#  pod 'NrLottieMixView', :path => '../CommonPods/NrLottieMixView/'

  
  
  # Pods for DarkStar
  pod 'AFNetworking', '~> 4.0'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'FMDB'
  pod 'Masonry'
  pod 'MBProgressHUD'  #弹窗
  pod 'YYCache'
  pod 'JXCategoryView'
  pod 'CTMediator'
end
