use_frameworks!

platform :ios, '10.0'

target 'DarkStarUIComponents_Example' do
  pod 'DarkStarUIComponents', :path => '../'

  target 'DarkStarUIComponents_Tests' do
    inherit! :search_paths

    
  end
end
