# Uncomment the next line to define a global platform for your project
source 'https://gitee.com/tuay-orn/private-pods.git'
source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '9.0'

target 'TargetIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  #常用分类，宏定义
  pod 'NrBaseCoreKit'
  #封装视图base类
  pod 'NrViewKit'
  #常用组件
  pod 'NrUIComponents/NrButton'
  pod 'NrUIComponents/CollectionViewLayout'
  pod 'NrUIComponents/DialogDate'
  pod 'NrUIComponents/DialogSingleChoice'
  pod 'NrUIComponents/DialogMultiChoice'
  pod 'NrUIComponents/CardSwitch'
  
  pod 'YYModel'
#  
#  #QMUI
#  pod 'NrQMUI'
#  #大文件下载，断点续传
#  pod 'NrHWDownloadManager'
#  #应用保活
#  pod 'NrKeepAliveManager'
#  #录音
#  pod 'NrAudioRecorderKit'
#  #特殊节日灰色展示
#  pod 'NrGrayViewKit'
#  #权限申请
#  pod 'NrAuthorityKit'
#  #检查更新
#  pod 'NrUpdateSDK'
#  #扫描
#  pod 'NrScanKit'
#  #OC使用Lottie库
#  pod 'NrLottieBridge'
#  #界面管理
#  pod 'NrInterfaceManagerKit'
#
#  #常用工具
#  pod 'NrGeneralTools/NrBTHelp'
#  pod 'NrGeneralTools/IrregularElementsCreator'
#  #常用组件
#  pod 'NrUIComponents/AlertController'
#  pod 'NrUIComponents/CollectionViewLayout'

  pod 'DoraemonKit'
  # Pods for TargetIOS
end
