use_frameworks!

platform :ios, '10.0'

target 'DarkStarGeneralTools_Example' do
  pod 'DarkStarGeneralTools', :path => '../'

  target 'DarkStarGeneralTools_Tests' do
    inherit! :search_paths

    
  end
end
