use_frameworks!

platform :ios, '10.0'

target 'DarkStarAuthorityKit_Example' do
  pod 'DarkStarAuthorityKit', :path => '../'

  target 'DarkStarAuthorityKit_Tests' do
    inherit! :search_paths

    
  end
end
