use_frameworks!

platform :ios, '10.0'

target 'DarkStarKeepAliveManager_Example' do
  pod 'DarkStarKeepAliveManager', :path => '../'

  target 'DarkStarKeepAliveManager_Tests' do
    inherit! :search_paths

    
  end
end
