use_frameworks!

platform :ios, '10.0'

target 'DarkStarAudioRecorderKit_Example' do
  pod 'DarkStarAudioRecorderKit', :path => '../'

  target 'DarkStarAudioRecorderKit_Tests' do
    inherit! :search_paths

    
  end
end
