use_frameworks!

platform :ios, '10.0'

target 'DarkStarConfiguration_Example' do
  pod 'DarkStarConfiguration', :path => '../'

  target 'DarkStarConfiguration_Tests' do
    inherit! :search_paths

    
  end
end
