use_frameworks!

platform :ios, '10.0'

target 'DarkStarResourceKit_Example' do
  pod 'DarkStarResourceKit', :path => '../'

  target 'DarkStarResourceKit_Tests' do
    inherit! :search_paths

    
  end
end
